### ISSUE TITLE
Error when "next build"

### ISSUE THREAD

**Issue by marcosdpeon** [LiveDuo/destack#107]
> next build

info  - Linting and checking validity of types  
info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
info  - Using external babel configuration from <source_path>\.babelrc
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
[    ] info  - Generating static pages (0/6)
Error occurred prerendering page "/builder". Read more: https://nextjs.org/docs/messages/prerender-error
Error: ENOENT: no such file or directory, scandir '<source_path>\data'
    at Object.readdirSync (node:fs:1527:3)
    at readdirRecursive (<source_path>\node_modules\destack\build\server\index.js:1887:26)  
    at loadAllData (<source_path>\node_modules\destack\build\server\index.js:1949:17)       
    at getStaticProps (<source_path>\node_modules\destack\build\server\index.js:2040:24)    
    at renderToHTML (<source_path>\node_modules\next\dist\server\render.js:386:26)
    at async <source_path>\node_modules\next\dist\export\worker.js:304:36
    at async Span.traceAsyncFn (<source_path>\node_modules\next\dist\trace\trace.js:79:20)  
info  - Generating static pages (6/6)

The builder.js page is like as below:

```
import { ContentProviderGrapes } from 'destack'
import 'grapesjs/dist/css/grapes.min.css'
import MiniHeader from '../components/Layout/MiniHeader'

export { getStaticProps } from 'destack/build/server'

const Builder = (props) => { 
    return (
        <div style={{height: '100%'}}>
            <MiniHeader />
            <ContentProviderGrapes {...props}/>
        </div>
    );
};

export default Builder;
```

**Comment by marcosdpeon** [comment]
I resolved it myself by adding the directory, "data", in the project folder.
